[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
ui_base = { path = "../base" }
ui_web = { path = "../web" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ui_native = { path = "../native" }
