[package]
name = "ui_native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
ui_base = { path = "../base" }
cfg-if = "1.0.0"
wgpu = "0.12.0"
wgpu_text = "0.6.1"
winit = "0.26.1"
bytemuck = { version = "1.9.1", features = [ "derive" ] }
